[package]
name = "hufu-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hufu-types = { path = "../hufu-types" }
hufu-dict = { path = "../hufu-dict" }
hufu-engine = { path = "../hufu-engine" }
hufu-config = { path = "../hufu-config" }
hufu-sentence = { path = "../hufu-sentence" }
hufu-rerank = { path = "../hufu-rerank" }
serde_json = { workspace = true }
